print("Example 1")
f = open("demofile.txt", "r")
print(f.read())
print("\nExample 2")
f = open("demofile.txt", "r")
print(f.read(7))
print("\nExample 3")
f = open("demofile.txt", "r")
print(f.readline())
print("\nExample 4")
f = open("demofile.txt", "r")
print(f.readline())
print(f.readline())
print("\nExample 5")
f = open("demofile.txt", "r")
for x in f:
    print(x)
print("\nExample 6")
f = open("demofile.txt", "r")
print(f.readline())
f.close()
print("\nExample 7")
f = open("demofile2.txt", "a")
f.write(" Now the file has more content! ")
f.close()
f = open("demofile2.txt", "r")
print(f.read())
print("\nExample 8")
f = open("demofile2.txt", "w")
f.write("Woops! I have deleted the content! ")
f.close()
f = open("demofile2.txt", "r")
print(f.read())
print("\nExample 9")
f = open("myfile.txt", "x")
print("\nExample 10")
import os
os.remove("demofile.txt")
print("\nExample 11")
import os
if os.path.exists("demofile.txt"):
    os.remove("demofile.txt")
else:
    print("The file dose not exist")
